name: build_and_deploy_to_firebase

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - name: slack notification
        uses: 8398a7/action-slack@v2
        if: always()
        with:
          status: ${{ job.status }}
          username: github-functions
          icon_emoji: ':octocat:'
          text: "ビルドはじまるよ :parrot:"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: pub get and build_runner build
        run: |
          cd functions
          pub get
          pub run build_runner build --output=build
          npm install
          rm build/node/packages

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: slack notification
        uses: 8398a7/action-slack@v2
        if: success()
        with:
          type: success
          status: ${{ job.status }}
          username: github-functions
          icon_emoji: ':octocat:'
          text: "ビルドデプロイせいこう :wave1parrot::wave2parrot::wave3parrot::wave4parrot::wave5parrot::wave6parrot::wave7parrot::wave8parrot::wave9parrot:"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: slack notification
        uses: 8398a7/action-slack@v2
        if: failure()
        with:
          type: failure
          status: ${{ job.status }}
          username: github-functions
          icon_emoji: ':octocat:'
          text: "ビルドデプロイしっぱい :ripparrot:"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

